import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "hy" | "fr" | "zh";

export const languageNames: Record<Language, string> = {
  en: "EN",
  ru: "РУ",
  hy: "ՀՅ",
  fr: "FR",
  zh: "中文",
};

export const languageFullNames: Record<Language, string> = {
  en: "English",
  ru: "Русский",
  hy: "Հայերեն",
  fr: "Français",
  zh: "中文",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home", "nav.menu": "Menu", "nav.about": "About", "nav.gallery": "Gallery", "nav.contact": "Contact", "nav.reserve": "Reserve",
    "home.est": "Est. 2012 · New York City", "home.tagline": "A Table Worth Remembering", "home.book": "✦ Book a Table", "home.viewMenu": "View Menu", "home.scroll": "Scroll",
    "home.philosophy": "Our Philosophy", "home.soulTitle": "Food is the language of the", "home.soul": "soul",
    "home.intro1": "Velvet Fork was born from a simple conviction: that a great meal is more than sustenance — it is art, ritual, and connection. Our kitchen breathes with seasonal ingredients sourced from trusted farms and artisan producers across the Northeast.",
    "home.intro2": "Every dish on our menu carries intention. Our chefs don't follow trends — they create experiences, drawing on classical French technique and the boldness of contemporary American cuisine.",
    "home.ourStory": "Our Story →", "home.yearsExcellence": "Years of Excellence",
    "home.chefsSelections": "Chef's Selections", "home.featured": "Featured", "home.dishes": "Dishes", "home.viewFullMenu": "View Full Menu →",
    "home.guestReviews": "Guest Reviews", "home.whatGuests": "What our guests", "home.say": "say",
    "menu.our": "Our", "menu.menu": "Menu", "menu.subtitle": "Curated Selections", "menu.starters": "Starters", "menu.mainCourse": "Main Course", "menu.desserts": "Desserts", "menu.drinks": "Drinks",
    "about.our": "Our", "about.story": "Story", "about.subtitle": "Who We Are", "about.beginning": "The Beginning", "about.bornFrom": "Born from", "about.passion": "Passion",
    "about.intro1": "In 2012, Chef Isabelle Fontaine returned to New York after a decade in Lyon, Paris, and Tokyo, carrying with her a singular vision: to create a dining room where food could be quietly extraordinary.",
    "about.intro2": "She found an old warehouse in the Meatpacking District with 14-foot ceilings. Her partner, architect Marcus Webb, transformed it into the intimate, candlelit sanctuary you see today.",
    "about.intro3": "Today, we seat 64 guests each evening across a single dining room, with a private chef's table for up to eight. Every reservation is a conversation with our kitchen, with the seasons, with the farmers whose labor fills each plate.",
    "about.diningCaption": "Velvet Fork dining room, 2018", "about.people": "The People Behind the Plates", "about.meetTeam": "Meet the Team",
    "about.seats": "Seats, by design", "about.seasonal": "Seasonal ingredients", "about.stars": "Michelin Stars",
    "gallery.our": "Our", "gallery.gallery": "Gallery", "gallery.subtitle": "Visual Stories",
    "contact.getIn": "Get in", "contact.touch": "Touch", "contact.subtitle": "Contact Us",
    "contact.address": "Address", "contact.phone": "Phone", "contact.email": "Email", "contact.hours": "Opening Hours",
    "contact.sendMessage": "Send a Message", "contact.name": "Name", "contact.yourName": "Your name", "contact.yourEmail": "your@email.com",
    "contact.message": "Message", "contact.yourMessage": "Your message...", "contact.send": "Send Message", "contact.sending": "Sending...",
    "contact.sent": "Message Sent", "contact.sentDesc": "We'll get back to you soon.",
    "reserve.reserveA": "Reserve a", "reserve.table": "Table", "reserve.subtitle": "Join Us", "reserve.reservations": "Reservations",
    "reserve.bookEvening": "Book Your Evening", "reserve.bookDesc": "We accept reservations up to 60 days in advance. For parties of 9 or more, please contact us directly.",
    "reserve.fullName": "Full Name", "reserve.phone": "Phone Number", "reserve.email": "Email Address", "reserve.partySize": "Party Size",
    "reserve.guest": "Guest", "reserve.guests": "Guests", "reserve.date": "Preferred Date", "reserve.time": "Preferred Time",
    "reserve.specialRequests": "Special Requests", "reserve.specialPlaceholder": "Dietary restrictions, celebrations, seating preferences...",
    "reserve.submit": "Confirm Reservation", "reserve.submitting": "Submitting...",
    "reserve.received": "Reservation Received", "reserve.receivedDesc": "We'll confirm your booking via email within 24 hours. For immediate assistance, call +1 (212) 555-0178.",
    "footer.desc": "A fine dining experience where classical technique meets contemporary vision. Every plate is a story, every evening a memory.",
    "footer.navigation": "Navigation", "footer.hours": "Hours", "footer.contact": "Contact",
    "footer.brunch": "Brunch: Sat & Sun 11 AM – 2 PM", "footer.rights": "© 2010–2011 Velvet Fork. All rights reserved.", "footer.designed": "Designed with passion in NYC",
    "admin.management": "Management", "admin.title": "Admin Panel", "admin.signOut": "Sign Out",
    "admin.dashboard": "Dashboard", "admin.reservations": "Reservations", "admin.messages": "Messages", "admin.settings": "Settings",
    "admin.totalReservations": "Total Reservations", "admin.pending": "Pending", "admin.totalGuests": "Total Guests", "admin.newMessages": "New Messages",
    "admin.recentReservations": "Recent Reservations", "admin.guest": "Guest", "admin.date": "Date", "admin.time": "Time", "admin.party": "Party", "admin.status": "Status", "admin.actions": "Actions",
    "admin.noReservations": "No reservations yet", "admin.noMessages": "No messages yet",
    "admin.backToList": "← Back to list", "admin.specialRequests": "Special Requests", "admin.none": "None",
    "admin.confirm": "Confirm", "admin.cancel": "Cancel", "admin.complete": "Complete", "admin.bookedOn": "Booked on",
    "admin.markRead": "Mark as read", "admin.delete": "Delete", "admin.loading": "Loading...", "admin.loadingData": "Loading data...",
    "login.management": "Management", "login.title": "Admin Login", "login.email": "Email", "login.password": "Password", "login.signIn": "Sign In", "login.signingIn": "Signing in...",
    "password.title": "Change Password", "password.new": "New Password", "password.confirm": "Confirm Password", "password.update": "Update Password", "password.updating": "Updating...",
    "auth.welcome": "Welcome", "auth.signIn": "Sign In", "auth.signUp": "Sign Up", "auth.email": "Email", "auth.password": "Password", "auth.confirmPassword": "Confirm Password",
    "auth.signingIn": "Signing in...", "auth.signingUp": "Signing up...", "auth.noAccount": "Don't have an account?", "auth.hasAccount": "Already have an account?",
    "auth.loginSuccess": "Logged in successfully", "auth.registerSuccess": "Account created! Please check your email to verify.", "auth.passwordMismatch": "Passwords do not match", "auth.passwordMin": "Password must be at least 6 characters",
    "auth.loginRequired": "Please sign in to continue",
    "auth.signOut": "Sign Out",
    "auth.forgotPassword": "Forgot password?",
    "auth.forgotDesc": "Enter your email and we'll send you a reset link.",
    "auth.sendResetLink": "Send Reset Link",
    "auth.sending": "Sending...",
    "auth.backToLogin": "Back to login",
    "auth.resetEmailSent": "Reset link sent! Check your email.",
    "auth.resetPassword": "Reset Password",
    "auth.newPassword": "New Password",
    "auth.passwordResetSuccess": "Password updated successfully!",
    "auth.invalidResetLink": "Invalid or expired reset link.",
  },
  ru: {
    "nav.home": "Главная", "nav.menu": "Меню", "nav.about": "О нас", "nav.gallery": "Галерея", "nav.contact": "Контакты", "nav.reserve": "Бронь",
    "home.est": "Осн. 2012 · Нью-Йорк", "home.tagline": "Стол, который запомнится", "home.book": "✦ Забронировать", "home.viewMenu": "Смотреть меню", "home.scroll": "Прокрутка",
    "home.philosophy": "Наша философия", "home.soulTitle": "Еда — это язык", "home.soul": "души",
    "home.intro1": "Velvet Fork родился из простого убеждения: что великолепная еда — это не просто пропитание — это искусство, ритуал и связь. Наша кухня дышит сезонными ингредиентами от проверенных фермеров.",
    "home.intro2": "Каждое блюдо в нашем меню несёт замысел. Наши шеф-повара не следуют трендам — они создают впечатления, опираясь на классическую французскую технику и смелость современной американской кухни.",
    "home.ourStory": "Наша история →", "home.yearsExcellence": "Лет совершенства",
    "home.chefsSelections": "Выбор шефа", "home.featured": "Избранные", "home.dishes": "блюда", "home.viewFullMenu": "Полное меню →",
    "home.guestReviews": "Отзывы гостей", "home.whatGuests": "Что говорят", "home.say": "гости",
    "menu.our": "Наше", "menu.menu": "Меню", "menu.subtitle": "Избранные блюда", "menu.starters": "Закуски", "menu.mainCourse": "Основные блюда", "menu.desserts": "Десерты", "menu.drinks": "Напитки",
    "about.our": "Наша", "about.story": "история", "about.subtitle": "Кто мы", "about.beginning": "Начало", "about.bornFrom": "Рождённый из", "about.passion": "страсти",
    "about.intro1": "В 2012 году шеф-повар Изабель Фонтен вернулась в Нью-Йорк после десятилетия в Лионе, Париже и Токио с единственной мечтой: создать ресторан, где еда была бы тихо необычной.",
    "about.intro2": "Она нашла старый склад в Meatpacking District с 4-метровыми потолками. Её партнёр, архитектор Маркус Уэбб, превратил его в интимное святилище при свечах.",
    "about.intro3": "Сегодня мы принимаем 64 гостя каждый вечер в едином зале с отдельным столом шеф-повара на восемь персон.",
    "about.diningCaption": "Зал Velvet Fork, 2018", "about.people": "Люди за тарелками", "about.meetTeam": "Наша команда",
    "about.seats": "Мест по дизайну", "about.seasonal": "Сезонные ингредиенты", "about.stars": "Звёзд Мишлен",
    "gallery.our": "Наша", "gallery.gallery": "Галерея", "gallery.subtitle": "Визуальные истории",
    "contact.getIn": "Связаться", "contact.touch": "с нами", "contact.subtitle": "Контакты",
    "contact.address": "Адрес", "contact.phone": "Телефон", "contact.email": "Эл. почта", "contact.hours": "Часы работы",
    "contact.sendMessage": "Написать сообщение", "contact.name": "Имя", "contact.yourName": "Ваше имя", "contact.yourEmail": "ваш@email.com",
    "contact.message": "Сообщение", "contact.yourMessage": "Ваше сообщение...", "contact.send": "Отправить", "contact.sending": "Отправка...",
    "contact.sent": "Сообщение отправлено", "contact.sentDesc": "Мы свяжемся с вами в ближайшее время.",
    "reserve.reserveA": "Забронировать", "reserve.table": "стол", "reserve.subtitle": "Присоединяйтесь", "reserve.reservations": "Бронирование",
    "reserve.bookEvening": "Забронируйте вечер", "reserve.bookDesc": "Мы принимаем бронирования за 60 дней. Для групп от 9 человек, пожалуйста, свяжитесь с нами напрямую.",
    "reserve.fullName": "Полное имя", "reserve.phone": "Телефон", "reserve.email": "Эл. почта", "reserve.partySize": "Количество гостей",
    "reserve.guest": "Гость", "reserve.guests": "Гостей", "reserve.date": "Дата", "reserve.time": "Время",
    "reserve.specialRequests": "Особые пожелания", "reserve.specialPlaceholder": "Диетические ограничения, праздники, предпочтения по рассадке...",
    "reserve.submit": "Подтвердить бронь", "reserve.submitting": "Отправка...",
    "reserve.received": "Бронирование получено", "reserve.receivedDesc": "Мы подтвердим вашу бронь по электронной почте в течение 24 часов.",
    "footer.desc": "Изысканная кухня, где классическая техника встречает современное видение. Каждое блюдо — история, каждый вечер — воспоминание.",
    "footer.navigation": "Навигация", "footer.hours": "Часы работы", "footer.contact": "Контакты",
    "footer.brunch": "Бранч: Сб и Вс 11:00 – 14:00", "footer.rights": "© 2010–2011 Velvet Fork. Все права защищены.", "footer.designed": "Создано с любовью в Нью-Йорке",
    "admin.management": "Управление", "admin.title": "Панель администратора", "admin.signOut": "Выйти",
    "admin.dashboard": "Панель", "admin.reservations": "Бронирования", "admin.messages": "Сообщения", "admin.settings": "Настройки",
    "admin.totalReservations": "Всего бронирований", "admin.pending": "Ожидающие", "admin.totalGuests": "Всего гостей", "admin.newMessages": "Новые сообщения",
    "admin.recentReservations": "Последние бронирования", "admin.guest": "Гость", "admin.date": "Дата", "admin.time": "Время", "admin.party": "Гости", "admin.status": "Статус", "admin.actions": "Действия",
    "admin.noReservations": "Пока нет бронирований", "admin.noMessages": "Пока нет сообщений",
    "admin.backToList": "← Назад к списку", "admin.specialRequests": "Особые пожелания", "admin.none": "Нет",
    "admin.confirm": "Подтвердить", "admin.cancel": "Отменить", "admin.complete": "Завершить", "admin.bookedOn": "Забронировано",
    "admin.markRead": "Отметить прочитанным", "admin.delete": "Удалить", "admin.loading": "Загрузка...", "admin.loadingData": "Загрузка данных...",
    "login.management": "Управление", "login.title": "Вход администратора", "login.email": "Эл. почта", "login.password": "Пароль", "login.signIn": "Войти", "login.signingIn": "Вход...",
    "password.title": "Сменить пароль", "password.new": "Новый пароль", "password.confirm": "Подтвердите пароль", "password.update": "Обновить пароль", "password.updating": "Обновление...",
    "auth.welcome": "Добро пожаловать", "auth.signIn": "Войти", "auth.signUp": "Регистрация", "auth.email": "Эл. почта", "auth.password": "Пароль", "auth.confirmPassword": "Подтвердите пароль",
    "auth.signingIn": "Вход...", "auth.signingUp": "Регистрация...", "auth.noAccount": "Нет аккаунта?", "auth.hasAccount": "Уже есть аккаунт?",
    "auth.loginSuccess": "Вы вошли успешно", "auth.registerSuccess": "Аккаунт создан! Проверьте почту.", "auth.passwordMismatch": "Пароли не совпадают", "auth.passwordMin": "Пароль минимум 6 символов",
    "auth.loginRequired": "Войдите, чтобы продолжить",
  },
  hy: {
    "nav.home": "Գլխավոր",
    "nav.menu": "Մենյու",
    "nav.about": "Մեր մասին",
    "nav.gallery": "Պատկերասրահ",
    "nav.contact": "Կապ",
    "nav.reserve": "Ամրագրել",
    "home.est": "Հիմն. 2012 · Նյու Յորք",
    "home.tagline": "Սեղան, որին արժի հիշել",
    "home.book": "✦ Ամրագրել սեղան",
    "home.viewMenu": "Տեսնել մենյուն",
    "home.scroll": "Ոլորել",
    "home.philosophy": "Մեր փիլիսոփայությունը",
    "home.soulTitle": "Սնունդը հոգու լեզուն է",
    "home.soul": "հոգու",
    "home.intro1": "Velvet Fork-ը ծնվել է մի պարզ համոզմունքից’ հանճավոր ուտելիքը ավելին է, քան սննդը’ արվեստ, ծես և կապ: Մեր խոհանոցը շնչում է սեզոնային բաղադրիչներով:",
    "home.intro2": "Մենյույի յուրաքանչյուր ուտելիք կրում է նպատակ: Մեր խոհարարները չեն հետևում թրենդներին’ նրանք ստեղծում են փորձառություններ:",
    "home.ourStory": "Մեր պատմությունը →",
    "home.yearsExcellence": "տարի գերազանցություն",
    "home.chefsSelections": "Խոհարարի ընտրությունը",
    "home.featured": "Ընտրանի",
    "home.dishes": "ուտեստներ",
    "home.viewFullMenu": "Տեսնել ամբողջ մենյուն →",
    "home.guestReviews": "Հյուրերի կարծիքները",
    "home.whatGuests": "Ինչ են ասում մեր",
    "home.say": "հյուրերը",
    "menu.our": "Մեր",
    "menu.menu": "Մենյուն",
    "menu.subtitle": "Ընտրանի ուտեստներ",
    "menu.starters": "Նախուտեստներ",
    "menu.mainCourse": "Հիմնական ուտեստ",
    "menu.desserts": "Աղանդեր",
    "menu.drinks": "Ըմպելիքներ",
    "about.our": "Մեր",
    "about.story": "պատմությունը",
    "about.subtitle": "Ովքեր ենք",
    "about.beginning": "Սկիզբը",
    "about.bornFrom": "Ծնված",
    "about.passion": "կիրքից",
    "about.intro1": "2012 թվականին շեֆ-խոհարար Իզաբել Ֆոնտենը վերադարձավ Նյու Յորք’ Միակ տեսլանելով այն վայրը, որտեղ ուտելիքը կարող էր լինել հանգիստ արտասովոր:",
    "about.intro2": "Նա գտավ հին պահեստ Մեթփաքինգ թաղամասում’ 4 մետր ավանով: Նրա գործընկերը՝ ճարտարապետ Մարկուս Ուեբը՝ այն վերածեց մտերիմ սրբազանի:",
    "about.intro3": "Այսօր մենք ընդունում ենք 64 հյուր ամեն երեկո միակ սրահում’ անձնական խոհարարի սեղանով’ ութի հոգու համար:",
    "about.diningCaption": "Velvet Fork սրահը, 2018",
    "about.people": "Մարդիկ ափսեների հետևում",
    "about.meetTeam": "Ծանոթացեք թիմին",
    "about.seats": "Նստատեղ, դիզայնով",
    "about.seasonal": "Սեզոնային բաղադրիչներ",
    "about.stars": "Միշլենի աստղեր",
    "gallery.our": "Մեր",
    "gallery.gallery": "Պատկերասրահը",
    "gallery.subtitle": "Տեսողական պատմություններ",
    "contact.getIn": "Կապվել",
    "contact.touch": "մեզ հետ",
    "contact.subtitle": "Կապ մեզ հետ",
    "contact.address": "Հասցե",
    "contact.phone": "Հեռախոս",
    "contact.email": "Էլ. փոստ",
    "contact.hours": "Աշխատանքային ժամեր",
    "contact.sendMessage": "Ուղարկել հաղորդագրություն",
    "contact.name": "Անուն",
    "contact.yourName": "Ձեր անունը",
    "contact.yourEmail": "ձեր@email.com",
    "contact.message": "Հաղորդագրություն",
    "contact.yourMessage": "Ձեր հաղորդագրությունը...",
    "contact.send": "Ուղարկել",
    "contact.sending": "Ուղարկվում է...",
    "contact.sent": "Հաղորդագրությունը ուղարկված է",
    "contact.sentDesc": "Մենք շուտով կպատասխանենք ձեզ:",
    "reserve.reserveA": "Ամրագրել",
    "reserve.table": "սեղան",
    "reserve.subtitle": "Միացեք մեզ",
    "reserve.reservations": "Ամրագրումներ",
    "reserve.bookEvening": "Ամրագրեք ձեր երեկոն",
    "reserve.bookDesc": "Մենք ընդունում ենք ամրագրումներ մինչև 60 օր առաջ: 9+ հոգու համար կապվեք ուղղակիորեն:",
    "reserve.fullName": "Լրիվ անուն",
    "reserve.phone": "Հեռախոս",
    "reserve.email": "Էլ. փոստ",
    "reserve.partySize": "Հյուրերի քանակը",
    "reserve.guest": "հյուր",
    "reserve.guests": "հյուր",
    "reserve.date": "Ամսաթիվ",
    "reserve.time": "Պամ",
    "reserve.specialRequests": "Հատուկ խնդրանքներ",
    "reserve.specialPlaceholder": "Սննդակարգի սահմանափակումներ, տոնակատարություններ...",
    "reserve.submit": "Հաստատել ամրագրումը",
    "reserve.submitting": "Ուղարկվում է...",
    "reserve.received": "Ամրագրումը ստացված է",
    "reserve.receivedDesc": "Մենք կհաստատենք ձեր ամրագրումը էլ. փոստով 24 ժամվա ընթացքում:",
    "footer.desc": "Բարձրակարգ խոհանոցական փորձառություն, որտեղ դասական տեխնիկան հանդիպում է ժամանակակից տեսլակետին:",
    "footer.navigation": "Նավիգացիա",
    "footer.hours": "Աշխատանքային ժամեր",
    "footer.contact": "Կապ",
    "footer.brunch": "Բրանչ. Շաբ և Կիր 11:00 – 14:00",
    "footer.rights": "© 2010–2011 Velvet Fork. Բոլոր իրավունքները պաշտպանված են:",
    "footer.designed": "Ստեղծված է կիրքով Նյու Յորքում",
    "admin.management": "Կառավարում",
    "admin.title": "Ադմին վահանակ",
    "admin.signOut": "Դուրս գալ",
    "admin.dashboard": "Վահանակ",
    "admin.reservations": "Ամրագրումներ",
    "admin.messages": "Հաղորդագրություններ",
    "admin.settings": "Կարգավորումներ",
    "admin.totalReservations": "Ընդամենը ամրագրումներ",
    "admin.pending": "Սպասվող",
    "admin.totalGuests": "Ընդամենը հյուրեր",
    "admin.newMessages": "Նոր հաղորդագրություններ",
    "admin.recentReservations": "Վերջին ամրագրումներ",
    "admin.guest": "Հյուր",
    "admin.date": "Ամսաթիվ",
    "admin.time": "Պամ",
    "admin.party": "Խումբ",
    "admin.status": "Կարգավիճակ",
    "admin.actions": "Գործողություններ",
    "admin.noReservations": "Ամրագրումներ դեռ չկան",
    "admin.noMessages": "Հաղորդագրություններ դեռ չկան",
    "admin.backToList": "← Վերադառնալ ցանկին",
    "admin.specialRequests": "Հատուկ խնդրանքներ",
    "admin.none": "Չկա",
    "admin.confirm": "Հաստատել",
    "admin.cancel": "Չեղարկել",
    "admin.complete": "Ավարտել",
    "admin.bookedOn": "Ամրագրված է",
    "admin.markRead": "Նշել կարդացած",
    "admin.delete": "Ջնջել",
    "admin.loading": "Բեռնվում է...",
    "admin.loadingData": "Տվյալները բեռնվում են...",
    "login.management": "Կառավարում",
    "login.title": "Ադմին մուտք",
    "login.email": "Էլ. փոստ",
    "login.password": "Գաղտնաբառ",
    "login.signIn": "Մուտք գործել",
    "login.signingIn": "Մուտք է գործվում...",
    "password.title": "Փոխել գաղտնաբառը",
    "password.new": "Նոր գաղտնաբառ",
    "password.confirm": "Հաստատել գաղտնաբառը",
    "password.update": "Թարմացնել",
    "password.updating": "Թարմացնվում է...",
    "auth.welcome": "Բdelays delays", "auth.signIn": "Մdelays", "auth.signUp": "Delaysdelaysdelays", "auth.email": "Delay. delays", "auth.password": "Delaysdelaysdelaysdelays", "auth.confirmPassword": "Delaysdelaysdelays delaysdelaysdelaysdelays",
    "auth.signingIn": "Delays...", "auth.signingUp": "Delaysdelaysdelays...", "auth.noAccount": "Delaysdelays delays?", "auth.hasAccount": "delays delays?",
    "auth.loginSuccess": "Delays delays", "auth.registerSuccess": "Delays delays!", "auth.passwordMismatch": "Delays delays", "auth.passwordMin": "delays 6 delays",
    "auth.loginRequired": "Delays delays",
  },
  fr: {
    "nav.home": "Accueil", "nav.menu": "Menu", "nav.about": "À propos", "nav.gallery": "Galerie", "nav.contact": "Contact", "nav.reserve": "Réserver",
    "home.est": "Fondé en 2012 · New York", "home.tagline": "Une table inoubliable", "home.book": "✦ Réserver une table", "home.viewMenu": "Voir le menu", "home.scroll": "Défiler",
    "home.philosophy": "Notre philosophie", "home.soulTitle": "La cuisine est le langage de", "home.soul": "l'âme",
    "home.intro1": "Velvet Fork est né d'une conviction simple : qu'un grand repas est plus qu'un sustentation — c'est de l'art, un rituel et une connexion. Notre cuisine respire avec des ingrédients de saison provenant de fermes de confiance.",
    "home.intro2": "Chaque plat de notre menu porte une intention. Nos chefs ne suivent pas les tendances — ils créent des expériences, s'appuyant sur la technique française classique et l'audace de la cuisine américaine contemporaine.",
    "home.ourStory": "Notre histoire →", "home.yearsExcellence": "Ans d'excellence",
    "home.chefsSelections": "Sélections du chef", "home.featured": "Plats", "home.dishes": "vedettes", "home.viewFullMenu": "Menu complet →",
    "home.guestReviews": "Avis des clients", "home.whatGuests": "Ce que disent nos", "home.say": "clients",
    "menu.our": "Notre", "menu.menu": "Menu", "menu.subtitle": "Sélections raffinées", "menu.starters": "Entrées", "menu.mainCourse": "Plats principaux", "menu.desserts": "Desserts", "menu.drinks": "Boissons",
    "about.our": "Notre", "about.story": "histoire", "about.subtitle": "Qui sommes-nous", "about.beginning": "Le début", "about.bornFrom": "Né de la", "about.passion": "passion",
    "about.intro1": "En 2012, la chef Isabelle Fontaine est revenue à New York après une décennie à Lyon, Paris et Tokyo, portant avec elle une vision singulière : créer une salle à manger où la cuisine serait discrètement extraordinaire.",
    "about.intro2": "Elle a trouvé un ancien entrepôt dans le Meatpacking District avec des plafonds de 4 mètres. Son partenaire, l'architecte Marcus Webb, l'a transformé en un sanctuaire intime éclairé aux bougies.",
    "about.intro3": "Aujourd'hui, nous accueillons 64 convives chaque soir dans une salle unique, avec une table du chef privée pour huit personnes.",
    "about.diningCaption": "Salle Velvet Fork, 2018", "about.people": "Les visages derrière les assiettes", "about.meetTeam": "Notre équipe",
    "about.seats": "Places, par design", "about.seasonal": "Ingrédients de saison", "about.stars": "Étoiles Michelin",
    "gallery.our": "Notre", "gallery.gallery": "Galerie", "gallery.subtitle": "Histoires visuelles",
    "contact.getIn": "Entrez en", "contact.touch": "contact", "contact.subtitle": "Contactez-nous",
    "contact.address": "Adresse", "contact.phone": "Téléphone", "contact.email": "E-mail", "contact.hours": "Heures d'ouverture",
    "contact.sendMessage": "Envoyer un message", "contact.name": "Nom", "contact.yourName": "Votre nom", "contact.yourEmail": "votre@email.com",
    "contact.message": "Message", "contact.yourMessage": "Votre message...", "contact.send": "Envoyer", "contact.sending": "Envoi en cours...",
    "contact.sent": "Message envoyé", "contact.sentDesc": "Nous vous répondrons bientôt.",
    "reserve.reserveA": "Réserver une", "reserve.table": "table", "reserve.subtitle": "Rejoignez-nous", "reserve.reservations": "Réservations",
    "reserve.bookEvening": "Réservez votre soirée", "reserve.bookDesc": "Nous acceptons les réservations jusqu'à 60 jours à l'avance. Pour les groupes de 9 ou plus, contactez-nous directement.",
    "reserve.fullName": "Nom complet", "reserve.phone": "Téléphone", "reserve.email": "Adresse e-mail", "reserve.partySize": "Nombre de convives",
    "reserve.guest": "Convive", "reserve.guests": "Convives", "reserve.date": "Date souhaitée", "reserve.time": "Heure souhaitée",
    "reserve.specialRequests": "Demandes spéciales", "reserve.specialPlaceholder": "Restrictions alimentaires, célébrations, préférences de placement...",
    "reserve.submit": "Confirmer la réservation", "reserve.submitting": "Envoi en cours...",
    "reserve.received": "Réservation reçue", "reserve.receivedDesc": "Nous confirmerons votre réservation par e-mail sous 24 heures.",
    "footer.desc": "Une expérience gastronomique où la technique classique rencontre la vision contemporaine. Chaque assiette est une histoire, chaque soirée un souvenir.",
    "footer.navigation": "Navigation", "footer.hours": "Horaires", "footer.contact": "Contact",
    "footer.brunch": "Brunch : Sam & Dim 11h – 14h", "footer.rights": "© 2010–2011 Velvet Fork. Tous droits réservés.", "footer.designed": "Conçu avec passion à NYC",
    "admin.management": "Gestion", "admin.title": "Panneau d'administration", "admin.signOut": "Déconnexion",
    "admin.dashboard": "Tableau de bord", "admin.reservations": "Réservations", "admin.messages": "Messages", "admin.settings": "Paramètres",
    "admin.totalReservations": "Total réservations", "admin.pending": "En attente", "admin.totalGuests": "Total convives", "admin.newMessages": "Nouveaux messages",
    "admin.recentReservations": "Réservations récentes", "admin.guest": "Client", "admin.date": "Date", "admin.time": "Heure", "admin.party": "Groupe", "admin.status": "Statut", "admin.actions": "Actions",
    "admin.noReservations": "Aucune réservation", "admin.noMessages": "Aucun message",
    "admin.backToList": "← Retour à la liste", "admin.specialRequests": "Demandes spéciales", "admin.none": "Aucune",
    "admin.confirm": "Confirmer", "admin.cancel": "Annuler", "admin.complete": "Terminer", "admin.bookedOn": "Réservé le",
    "admin.markRead": "Marquer comme lu", "admin.delete": "Supprimer", "admin.loading": "Chargement...", "admin.loadingData": "Chargement des données...",
    "login.management": "Gestion", "login.title": "Connexion admin", "login.email": "E-mail", "login.password": "Mot de passe", "login.signIn": "Se connecter", "login.signingIn": "Connexion...",
    "password.title": "Changer le mot de passe", "password.new": "Nouveau mot de passe", "password.confirm": "Confirmer le mot de passe", "password.update": "Mettre à jour", "password.updating": "Mise à jour...",
    "auth.welcome": "Bienvenue", "auth.signIn": "Se connecter", "auth.signUp": "S'inscrire", "auth.email": "E-mail", "auth.password": "Mot de passe", "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.signingIn": "Connexion...", "auth.signingUp": "Inscription...", "auth.noAccount": "Pas de compte ?", "auth.hasAccount": "Déjà un compte ?",
    "auth.loginSuccess": "Connecté avec succès", "auth.registerSuccess": "Compte créé ! Vérifiez votre e-mail.", "auth.passwordMismatch": "Les mots de passe ne correspondent pas", "auth.passwordMin": "Le mot de passe doit avoir au moins 6 caractères",
    "auth.loginRequired": "Veuillez vous connecter",
  },
  zh: {
    "nav.home": "首页", "nav.menu": "菜单", "nav.about": "关于", "nav.gallery": "画廊", "nav.contact": "联系", "nav.reserve": "预订",
    "home.est": "创立于2012年 · 纽约", "home.tagline": "值得铭记的餐桌", "home.book": "✦ 预订餐桌", "home.viewMenu": "查看菜单", "home.scroll": "滚动",
    "home.philosophy": "我们的理念", "home.soulTitle": "美食是", "home.soul": "灵魂的语言",
    "home.intro1": "Velvet Fork 诞生于一个简单的信念：美食不仅仅是食物——它是艺术、仪式和连接。我们的厨房充满来自东北部可信赖农场的时令食材。",
    "home.intro2": "菜单上的每道菜都承载着用心。我们的厨师不追随潮流——他们创造体验，融合经典法式技艺与当代美式烹饪的大胆。",
    "home.ourStory": "我们的故事 →", "home.yearsExcellence": "年卓越",
    "home.chefsSelections": "主厨精选", "home.featured": "精选", "home.dishes": "菜品", "home.viewFullMenu": "查看完整菜单 →",
    "home.guestReviews": "客人评价", "home.whatGuests": "客人们", "home.say": "怎么说",
    "menu.our": "我们的", "menu.menu": "菜单", "menu.subtitle": "精心挑选", "menu.starters": "前菜", "menu.mainCourse": "主菜", "menu.desserts": "甜点", "menu.drinks": "饮品",
    "about.our": "我们的", "about.story": "故事", "about.subtitle": "关于我们", "about.beginning": "开始", "about.bornFrom": "源于", "about.passion": "热情",
    "about.intro1": "2012年，主厨伊莎贝尔·方丹在里昂、巴黎和东京度过十年后回到纽约，带着一个独特的愿景：创造一个美食可以安静而非凡的餐厅。",
    "about.intro2": "她在肉库区找到了一个有4米高天花板的旧仓库。她的合伙人、建筑师马库斯·韦伯将它改造成了你今天看到的烛光圣殿。",
    "about.intro3": "如今，我们每晚在一个单独的餐厅接待64位客人，另有一张可容纳八人的私人厨师桌。",
    "about.diningCaption": "Velvet Fork 餐厅, 2018", "about.people": "盘中的面孔", "about.meetTeam": "认识团队",
    "about.seats": "设计座位", "about.seasonal": "时令食材", "about.stars": "米其林星",
    "gallery.our": "我们的", "gallery.gallery": "画廊", "gallery.subtitle": "视觉故事",
    "contact.getIn": "取得", "contact.touch": "联系", "contact.subtitle": "联系我们",
    "contact.address": "地址", "contact.phone": "电话", "contact.email": "电子邮件", "contact.hours": "营业时间",
    "contact.sendMessage": "发送消息", "contact.name": "姓名", "contact.yourName": "您的姓名", "contact.yourEmail": "您的邮箱",
    "contact.message": "消息", "contact.yourMessage": "您的消息...", "contact.send": "发送消息", "contact.sending": "发送中...",
    "contact.sent": "消息已发送", "contact.sentDesc": "我们会尽快回复您。",
    "reserve.reserveA": "预订", "reserve.table": "餐桌", "reserve.subtitle": "加入我们", "reserve.reservations": "预订",
    "reserve.bookEvening": "预订您的晚餐", "reserve.bookDesc": "我们接受提前60天的预订。9人以上的团体请直接联系我们。",
    "reserve.fullName": "全名", "reserve.phone": "电话", "reserve.email": "电子邮件", "reserve.partySize": "人数",
    "reserve.guest": "位客人", "reserve.guests": "位客人", "reserve.date": "日期", "reserve.time": "时间",
    "reserve.specialRequests": "特殊要求", "reserve.specialPlaceholder": "饮食限制、庆祝活动、座位偏好...",
    "reserve.submit": "确认预订", "reserve.submitting": "提交中...",
    "reserve.received": "预订已收到", "reserve.receivedDesc": "我们将在24小时内通过电子邮件确认您的预订。",
    "footer.desc": "经典技艺与当代视野相遇的高级餐饮体验。每盘是一个故事，每晚是一段记忆。",
    "footer.navigation": "导航", "footer.hours": "营业时间", "footer.contact": "联系",
    "footer.brunch": "早午餐：周六和周日 11:00 – 14:00", "footer.rights": "© 2010–2011 Velvet Fork. 保留所有权利。", "footer.designed": "在纽约用心设计",
    "admin.management": "管理", "admin.title": "管理面板", "admin.signOut": "退出",
    "admin.dashboard": "仪表板", "admin.reservations": "预订", "admin.messages": "消息", "admin.settings": "设置",
    "admin.totalReservations": "总预订数", "admin.pending": "待处理", "admin.totalGuests": "总客人数", "admin.newMessages": "新消息",
    "admin.recentReservations": "最近预订", "admin.guest": "客人", "admin.date": "日期", "admin.time": "时间", "admin.party": "人数", "admin.status": "状态", "admin.actions": "操作",
    "admin.noReservations": "暂无预订", "admin.noMessages": "暂无消息",
    "admin.backToList": "← 返回列表", "admin.specialRequests": "特殊要求", "admin.none": "无",
    "admin.confirm": "确认", "admin.cancel": "取消", "admin.complete": "完成", "admin.bookedOn": "预订于",
    "admin.markRead": "标记已读", "admin.delete": "删除", "admin.loading": "加载中...", "admin.loadingData": "加载数据...",
    "login.management": "管理", "login.title": "管理员登录", "login.email": "电子邮件", "login.password": "密码", "login.signIn": "登录", "login.signingIn": "登录中...",
    "password.title": "修改密码", "password.new": "新密码", "password.confirm": "确认密码", "password.update": "更新密码", "password.updating": "更新中...",
    "auth.welcome": "欢迎", "auth.signIn": "登录", "auth.signUp": "注册", "auth.email": "电子邮件", "auth.password": "密码", "auth.confirmPassword": "确认密码",
    "auth.signingIn": "登录中...", "auth.signingUp": "注册中...", "auth.noAccount": "没有账户？", "auth.hasAccount": "已有账户？",
    "auth.loginSuccess": "登录成功", "auth.registerSuccess": "账户已创建！请检查邮箱。", "auth.passwordMismatch": "密码不匹配", "auth.passwordMin": "密码至少6个字符",
    "auth.loginRequired": "请登录以继续",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("vf-lang");
    return (saved as Language) || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("vf-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
