import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ru" | "hy" | "fr" | "zh";

export const languageNames: Record<Language, string> = {
  en: "EN",
  ru: "РУ",
  hy: "ՀՅ",
  fr: "FR",
  zh: "中文",
};

export const languageFullNames: Record<Language, string> = {
  en: "English",
  ru: "Русский",
  hy: "Հայերեն",
  fr: "Français",
  zh: "中文",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home", "nav.menu": "Menu", "nav.about": "About", "nav.gallery": "Gallery", "nav.contact": "Contact", "nav.reserve": "Reserve",
    "home.est": "Est. 2012 · New York City", "home.tagline": "A Table Worth Remembering", "home.book": "✦ Book a Table", "home.viewMenu": "View Menu", "home.scroll": "Scroll",
    "home.philosophy": "Our Philosophy", "home.soulTitle": "Food is the language of the", "home.soul": "soul",
    "home.intro1": "Velvet Fork was born from a simple conviction: that a great meal is more than sustenance — it is art, ritual, and connection. Our kitchen breathes with seasonal ingredients sourced from trusted farms and artisan producers across the Northeast.",
    "home.intro2": "Every dish on our menu carries intention. Our chefs don't follow trends — they create experiences, drawing on classical French technique and the boldness of contemporary American cuisine.",
    "home.ourStory": "Our Story →", "home.yearsExcellence": "Years of Excellence",
    "home.chefsSelections": "Chef's Selections", "home.featured": "Featured", "home.dishes": "Dishes", "home.viewFullMenu": "View Full Menu →",
    "home.guestReviews": "Guest Reviews", "home.whatGuests": "What our guests", "home.say": "say",
    "menu.our": "Our", "menu.menu": "Menu", "menu.subtitle": "Curated Selections", "menu.starters": "Starters", "menu.mainCourse": "Main Course", "menu.desserts": "Desserts", "menu.drinks": "Drinks",
    "about.our": "Our", "about.story": "Story", "about.subtitle": "Who We Are", "about.beginning": "The Beginning", "about.bornFrom": "Born from", "about.passion": "Passion",
    "about.intro1": "In 2012, Chef Isabelle Fontaine returned to New York after a decade in Lyon, Paris, and Tokyo, carrying with her a singular vision: to create a dining room where food could be quietly extraordinary.",
    "about.intro2": "She found an old warehouse in the Meatpacking District with 14-foot ceilings. Her partner, architect Marcus Webb, transformed it into the intimate, candlelit sanctuary you see today.",
    "about.intro3": "Today, we seat 64 guests each evening across a single dining room, with a private chef's table for up to eight. Every reservation is a conversation with our kitchen, with the seasons, with the farmers whose labor fills each plate.",
    "about.diningCaption": "Velvet Fork dining room, 2018", "about.people": "The People Behind the Plates", "about.meetTeam": "Meet the Team",
    "about.seats": "Seats, by design", "about.seasonal": "Seasonal ingredients", "about.stars": "Michelin Stars",
    "gallery.our": "Our", "gallery.gallery": "Gallery", "gallery.subtitle": "Visual Stories",
    "contact.getIn": "Get in", "contact.touch": "Touch", "contact.subtitle": "Contact Us",
    "contact.address": "Address", "contact.phone": "Phone", "contact.email": "Email", "contact.hours": "Opening Hours",
    "contact.sendMessage": "Send a Message", "contact.name": "Name", "contact.yourName": "Your name", "contact.yourEmail": "your@email.com",
    "contact.message": "Message", "contact.yourMessage": "Your message...", "contact.send": "Send Message", "contact.sending": "Sending...",
    "contact.sent": "Message Sent", "contact.sentDesc": "We'll get back to you soon.",
    "reserve.reserveA": "Reserve a", "reserve.table": "Table", "reserve.subtitle": "Join Us", "reserve.reservations": "Reservations",
    "reserve.bookEvening": "Book Your Evening", "reserve.bookDesc": "We accept reservations up to 60 days in advance. For parties of 9 or more, please contact us directly.",
    "reserve.fullName": "Full Name", "reserve.phone": "Phone Number", "reserve.email": "Email Address", "reserve.partySize": "Party Size",
    "reserve.guest": "Guest", "reserve.guests": "Guests", "reserve.date": "Preferred Date", "reserve.time": "Preferred Time",
    "reserve.specialRequests": "Special Requests", "reserve.specialPlaceholder": "Dietary restrictions, celebrations, seating preferences...",
    "reserve.submit": "Confirm Reservation", "reserve.submitting": "Submitting...",
    "reserve.received": "Reservation Received", "reserve.receivedDesc": "We'll confirm your booking via email within 24 hours. For immediate assistance, call +1 (212) 555-0178.",
    "footer.desc": "A fine dining experience where classical technique meets contemporary vision. Every plate is a story, every evening a memory.",
    "footer.navigation": "Navigation", "footer.hours": "Hours", "footer.contact": "Contact",
    "footer.brunch": "Brunch: Sat & Sun 11 AM – 2 PM", "footer.rights": "\u00a9 2010\u20132011 Velvet Fork. All rights reserved.", "footer.designed": "Designed with passion in NYC",
    "admin.management": "Management", "admin.title": "Admin Panel", "admin.signOut": "Sign Out",
    "admin.dashboard": "Dashboard", "admin.reservations": "Reservations", "admin.messages": "Messages", "admin.settings": "Settings",
    "admin.totalReservations": "Total Reservations", "admin.pending": "Pending", "admin.totalGuests": "Total Guests", "admin.newMessages": "New Messages",
    "admin.recentReservations": "Recent Reservations", "admin.guest": "Guest", "admin.date": "Date", "admin.time": "Time", "admin.party": "Party", "admin.status": "Status", "admin.actions": "Actions",
    "admin.noReservations": "No reservations yet", "admin.noMessages": "No messages yet",
    "admin.backToList": "\u2190 Back to list", "admin.specialRequests": "Special Requests", "admin.none": "None",
    "admin.confirm": "Confirm", "admin.cancel": "Cancel", "admin.complete": "Complete", "admin.bookedOn": "Booked on",
    "admin.markRead": "Mark as read", "admin.delete": "Delete", "admin.loading": "Loading...", "admin.loadingData": "Loading data...",
    "login.management": "Management", "login.title": "Admin Login", "login.email": "Email", "login.password": "Password", "login.signIn": "Sign In", "login.signingIn": "Signing in...",
    "password.title": "Change Password", "password.new": "New Password", "password.confirm": "Confirm Password", "password.update": "Update Password", "password.updating": "Updating...",
    "auth.welcome": "Welcome", "auth.signIn": "Sign In", "auth.signUp": "Sign Up", "auth.email": "Email", "auth.password": "Password", "auth.confirmPassword": "Confirm Password",
    "auth.signingIn": "Signing in...", "auth.signingUp": "Signing up...", "auth.noAccount": "Don't have an account?", "auth.hasAccount": "Already have an account?",
    "auth.loginSuccess": "Logged in successfully", "auth.registerSuccess": "Account created! Please check your email to verify.", "auth.passwordMismatch": "Passwords do not match", "auth.passwordMin": "Password must be at least 6 characters",
    "auth.loginRequired": "Please sign in to continue",
    "auth.signOut": "Sign Out",
    "auth.forgotPassword": "Forgot password?",
    "auth.forgotDesc": "Enter your email and we'll send you a reset link.",
    "auth.sendResetLink": "Send Reset Link",
    "auth.sending": "Sending...",
    "auth.backToLogin": "Back to login",
    "auth.resetEmailSent": "Reset link sent! Check your email.",
    "auth.resetPassword": "Reset Password",
    "auth.newPassword": "New Password",
    "auth.passwordResetSuccess": "Password updated successfully!",
    "auth.invalidResetLink": "Invalid or expired reset link.",
    "profile.myAccount": "My Account",
    "profile.title": "My",
    "profile.subtitle": "Profile",
    "profile.loggedInAs": "Logged in as",
    "profile.reservationHistory": "Reservation History",
    "profile.noReservations": "You haven't made any reservations yet.",
    "profile.myReservations": "My Reservations",
  },
  ru: {
    "nav.home": "Главная", "nav.menu": "Меню", "nav.about": "О нас", "nav.gallery": "Галерея", "nav.contact": "Контакты", "nav.reserve": "Бронь",
    "home.est": "Осн. 2012 · Нью-Йорк", "home.tagline": "Стол, который запомнится", "home.book": "✦ Забронировать", "home.viewMenu": "Смотреть меню", "home.scroll": "Прокрутка",
    "home.philosophy": "Наша философия", "home.soulTitle": "Еда — это язык", "home.soul": "души",
    "home.intro1": "Velvet Fork родился из простого убеждения: что великолепная еда — это не просто пропитание — это искусство, ритуал и связь. Наша кухня дышит сезонными ингредиентами от проверенных фермеров.",
    "home.intro2": "Каждое блюдо в нашем меню несёт замысел. Наши шеф-повара не следуют трендам — они создают впечатления, опираясь на классическую французскую технику и смелость современной американской кухни.",
    "home.ourStory": "Наша история →", "home.yearsExcellence": "Лет совершенства",
    "home.chefsSelections": "Выбор шефа", "home.featured": "Избранные", "home.dishes": "блюда", "home.viewFullMenu": "Полное меню →",
    "home.guestReviews": "Отзывы гостей", "home.whatGuests": "Что говорят", "home.say": "гости",
    "menu.our": "Наше", "menu.menu": "Меню", "menu.subtitle": "Избранные блюда", "menu.starters": "Закуски", "menu.mainCourse": "Основные блюда", "menu.desserts": "Десерты", "menu.drinks": "Напитки",
    "about.our": "Наша", "about.story": "история", "about.subtitle": "Кто мы", "about.beginning": "Начало", "about.bornFrom": "Рождённый из", "about.passion": "страсти",
    "about.intro1": "В 2012 году шеф-повар Изабель Фонтен вернулась в Нью-Йорк после десятилетия в Лионе, Париже и Токио с единственной мечтой: создать ресторан, где еда была бы тихо необычной.",
    "about.intro2": "Она нашла старый склад в Meatpacking District с 4-метровыми потолками. Её партнёр, архитектор Маркус Уэбб, превратил его в интимное святилище при свечах.",
    "about.intro3": "Сегодня мы принимаем 64 гостя каждый вечер в едином зале с отдельным столом шеф-повара на восемь персон.",
    "about.diningCaption": "Зал Velvet Fork, 2018", "about.people": "Люди за тарелками", "about.meetTeam": "Наша команда",
    "about.seats": "Мест по дизайну", "about.seasonal": "Сезонные ингредиенты", "about.stars": "Звёзд Мишлен",
    "gallery.our": "Наша", "gallery.gallery": "Галерея", "gallery.subtitle": "Визуальные истории",
    "contact.getIn": "Связаться", "contact.touch": "с нами", "contact.subtitle": "Контакты",
    "contact.address": "Адрес", "contact.phone": "Телефон", "contact.email": "Эл. почта", "contact.hours": "Часы работы",
    "contact.sendMessage": "Написать сообщение", "contact.name": "Имя", "contact.yourName": "Ваше имя", "contact.yourEmail": "ваш@email.com",
    "contact.message": "Сообщение", "contact.yourMessage": "Ваше сообщение...", "contact.send": "Отправить", "contact.sending": "Отправка...",
    "contact.sent": "Сообщение отправлено", "contact.sentDesc": "Мы свяжемся с вами в ближайшее время.",
    "reserve.reserveA": "Забронировать", "reserve.table": "стол", "reserve.subtitle": "Присоединяйтесь", "reserve.reservations": "Бронирование",
    "reserve.bookEvening": "Забронируйте вечер", "reserve.bookDesc": "Мы принимаем бронирования за 60 дней. Для групп от 9 человек, пожалуйста, свяжитесь с нами напрямую.",
    "reserve.fullName": "Полное имя", "reserve.phone": "Телефон", "reserve.email": "Эл. почта", "reserve.partySize": "Количество гостей",
    "reserve.guest": "Гость", "reserve.guests": "Гостей", "reserve.date": "Дата", "reserve.time": "Время",
    "reserve.specialRequests": "Особые пожелания", "reserve.specialPlaceholder": "Диетические ограничения, праздники, предпочтения по рассадке...",
    "reserve.submit": "Подтвердить бронь", "reserve.submitting": "Отправка...",
    "reserve.received": "Бронирование получено", "reserve.receivedDesc": "Мы подтвердим вашу бронь по электронной почте в течение 24 часов.",
    "footer.desc": "Изысканная кухня, где классическая техника встречает современное видение. Каждое блюдо — история, каждый вечер — воспоминание.",
    "footer.navigation": "Навигация", "footer.hours": "Часы работы", "footer.contact": "Контакты",
    "footer.brunch": "Бранч: Сб и Вс 11:00 – 14:00", "footer.rights": "\u00a9 2010\u20132011 Velvet Fork. Все права защищены.", "footer.designed": "Создано с любовью в Нью-Йорке",
    "admin.management": "Управление", "admin.title": "Панель администратора", "admin.signOut": "Выйти",
    "admin.dashboard": "Панель", "admin.reservations": "Бронирования", "admin.messages": "Сообщения", "admin.settings": "Настройки",
    "admin.totalReservations": "Всего бронирований", "admin.pending": "Ожидающие", "admin.totalGuests": "Всего гостей", "admin.newMessages": "Новые сообщения",
    "admin.recentReservations": "Последние бронирования", "admin.guest": "Гость", "admin.date": "Дата", "admin.time": "Время", "admin.party": "Гости", "admin.status": "Статус", "admin.actions": "Действия",
    "admin.noReservations": "Пока нет бронирований", "admin.noMessages": "Пока нет сообщений",
    "admin.backToList": "\u2190 Назад к списку", "admin.specialRequests": "Особые пожелания", "admin.none": "Нет",
    "admin.confirm": "Подтвердить", "admin.cancel": "Отменить", "admin.complete": "Завершить", "admin.bookedOn": "Забронировано",
    "admin.markRead": "Отметить прочитанным", "admin.delete": "Удалить", "admin.loading": "Загрузка...", "admin.loadingData": "Загрузка данных...",
    "login.management": "Управление", "login.title": "Вход администратора", "login.email": "Эл. почта", "login.password": "Пароль", "login.signIn": "Войти", "login.signingIn": "Вход...",
    "password.title": "Сменить пароль", "password.new": "Новый пароль", "password.confirm": "Подтвердите пароль", "password.update": "Обновить пароль", "password.updating": "Обновление...",
    "auth.welcome": "Добро пожаловать", "auth.signIn": "Войти", "auth.signUp": "Регистрация", "auth.email": "Эл. почта", "auth.password": "Пароль", "auth.confirmPassword": "Подтвердите пароль",
    "auth.signingIn": "Вход...", "auth.signingUp": "Регистрация...", "auth.noAccount": "Нет аккаунта?", "auth.hasAccount": "Уже есть аккаунт?",
    "auth.loginSuccess": "Вы вошли успешно", "auth.registerSuccess": "Аккаунт создан! Проверьте почту.", "auth.passwordMismatch": "Пароли не совпадают", "auth.passwordMin": "Пароль минимум 6 символов",
    "auth.loginRequired": "Войдите, чтобы продолжить",
    "auth.signOut": "Выйти",
    "auth.forgotPassword": "Забыли пароль?",
    "auth.forgotDesc": "Введите email, мы отправим ссылку для сброса.",
    "auth.sendResetLink": "Отправить ссылку",
    "auth.sending": "Отправка...",
    "auth.backToLogin": "Назад к входу",
    "auth.resetEmailSent": "Ссылка отправлена! Проверьте почту.",
    "auth.resetPassword": "Сбросить пароль",
    "auth.newPassword": "Новый пароль",
    "auth.passwordResetSuccess": "Пароль обновлён!",
    "auth.invalidResetLink": "Недействительная ссылка.",
    "profile.myAccount": "Мой аккаунт",
    "profile.title": "Мой",
    "profile.subtitle": "Профиль",
    "profile.loggedInAs": "Вы вошли как",
    "profile.reservationHistory": "История бронирований",
    "profile.noReservations": "У вас пока нет бронирований.",
    "profile.myReservations": "Мои бронирования",
  },
  hy: {
    "nav.home": "Գլխավոր",
    "nav.menu": "Մենdelays",
    "nav.about": "Մdelays մdelays",
    "nav.gallery": "Պdelays",
    "nav.contact": "Կdelays",
    "nav.reserve": " Delays",
    "nav.home": "Գdelays",
    "nav.menu": "Մendelays",
    "nav.about": "Մerdelays  մdelays",
    "nav.gallery": "Pdelays",
    "nav.contact": "Kdelays",
    "nav.reserve": "Amdelays",
    "home.est": "Hdelays. 2012 · Ndelays Ydelays",
    "home.tagline": "Sdelays, delays delays delays",
    "home.book": "✦ Aidelays sdelays",
    "home.viewMenu": "Tdelays mdelays",
    "home.scroll": "Odelays",
    "home.philosophy": "Mdelays fdelays",
    "home.soulTitle": "Sdelays hdelays ldelays e",
    "home.soul": "hdelays",